### ISSUE TITLE
todo for 0.1.0

### ISSUE THREAD

**Issue by adamjmcgrath** [adamjmcgrath/react-native-simple-auth#1]
- [x] Unit tests
- [x] Travis build/test/deploy
- [x] secrets.js example
- [x] Finish install docs
- [x] Usage example (and test)
- [x] JS Doc
- [x] Get review for Objective-C code
